
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"  # WordPress accessible via http://<IP_VM>:8080
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: docker
    depends_on:
      - db

  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: docker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-trunk
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: docker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "10051:10051"  # Zabbix accessible via http://<IP_VM>:10051
    depends_on:
      - db

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-trunk
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: docker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Paris
    ports:
      - "8081:80"  # Zabbix accessible via http://<IP_VM>:8081
    depends_on:
      - zabbix-server

volumes:
  db_data:
